version: "3.3"

services:
  django:
    container_name: django
    build:
      context: ./mini7
      dockerfile: Dockerfile
    volumes:
      - ./mini7:/django
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_TIME_ZONE: ${DJANGO_TIME_ZONE}
      DJANGO_LANGUAGE_CODE: ${DJANGO_LANGUAGE_CODE}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_CSRF_TRUSTED_ORIGINS_NEXTJS: ${DJANGO_CSRF_TRUSTED_ORIGINS_NEXTJS}
      AI_BARD_SECRET_KEY: ${AI_BARD_SECRET_KEY}
      AI_CHATGPT_SECRET_KEY: ${AI_CHATGPT_SECRET_KEY}
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - server-network

  nginx:
    container_name: nginx
    restart: "always"
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - nextjs
      - django
    networks:
      - server-network

  nextjs:
    container_name: nextjs
    restart: "always"
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ENV_API_DOMAIN: ${NEXT_PUBLIC_ENV_API_DOMAIN}
        NEXT_PUBLIC_ENV_API_URL: ${NEXT_PUBLIC_ENV_API_URL}
        NEXT_PUBLIC_ENV_DOMAIN: ${NEXT_PUBLIC_ENV_DOMAIN}
        NEXT_PUBLIC_ENV_IMAGE_URL: ${NEXT_PUBLIC_ENV_IMAGE_URL}
    environment:
      TZ: "Asia/Seoul"
    networks:
      - server-network

networks:
  server-network:
